'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import CustomerBottomNav from '@/components/CustomerBottomNav';
import LoyaltyRedeem from '@/components/LoyaltyRedeem';
import LoyaltyEmailAuth from '@/components/LoyaltyEmailAuth';
import { supabaseBrowser } from '@/lib/supabaseBrowser';
import '../loja-v15.css';
export default function FidelidadePage(){
 const [telefone,setTelefone]=useState('');const [dados,setDados]=useState(null);const [loading,setLoading]=useState(false);const [erro,setErro]=useState('');const [autenticado,setAutenticado]=useState(false);
 useEffect(()=>{(async()=>{try{const c=JSON.parse(localStorage.getItem('jm_cliente')||'null');if(c?.telefone)setTelefone(c.telefone);const {data}=await supabaseBrowser().auth.getSession();if(data.session){setAutenticado(true);await consultarConta(data.session.access_token)}else if(c?.telefone)await consultar(c.telefone)}catch{}})()},[]);
 async function consultarConta(token){setErro('');setLoading(true);try{const r=await fetch('/api/fidelidade/conta',{headers:{Authorization:'Bearer '+token}});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Não foi possível consultar');setDados(d)}catch(e){setErro(e.message)}finally{setLoading(false)}}
 async function validarConta(session){try{const r=await fetch('/api/fidelidade/vincular',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({telefone})});const d=await r.json();if(!r.ok)throw new Error(d.erro);setAutenticado(true);await consultarConta(session.access_token)}catch(e){setErro(e.message)}}
 async function consultar(t=telefone){setErro('');setLoading(true);try{const r=await fetch('/api/fidelidade',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({telefone:t})});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Não foi possível consultar');setDados(d)}catch(e){setErro(e.message)}finally{setLoading(false)}}
 const saldo=dados?.cliente?.saldo||0;const pendentes=(dados?.movimentos||[]).filter(m=>m.status==='pendente').reduce((s,m)=>s+Number(m.pontos||0),0);
 return <div className="loyalty-page"><header className="loyalty-head"><Link href="/" aria-label="Voltar">‹</Link><div><span>JEITO DE MÃE</span><h1>Fidelidade</h1></div></header><main className="loyalty-content"><section className="loyalty-hero"><span className="loyalty-kicker">CLUBE JEITO DE MÃE</span><h2>Seu carinho pela nossa comida volta para você.</h2><p>Faça pedidos, acumule pontos e troque por recompensas.</p><div className="loyalty-balance"><div><small>Seu saldo</small><strong>{saldo} <em>pontos</em></strong>{pendentes>0&&<small>+ {pendentes} pontos aguardando conclusão</small>}</div><span>♡</span></div>{!autenticado&&telefone&&<LoyaltyEmailAuth onValidated={validarConta}/>} {!dados?.cliente&&!telefone&&<div className="loyalty-login"><input value={telefone} onChange={e=>setTelefone(e.target.value)} placeholder="Seu WhatsApp" inputMode="tel"/><button onClick={()=>consultar()} disabled={loading||!telefone}>{loading?'Consultando...':'Consultar meus pontos'}</button></div>}{erro&&<div className="customer-error">{erro}</div>}</section><section className="loyalty-how"><h3>Como funciona</h3><div><i>1</i><p><b>Peça pelo Jeito de Mãe</b><small>Faça seu pedido normalmente pelo cardápio.</small></p></div><div><i>2</i><p><b>Acumule pontos</b><small>Os pontos ficam pendentes até o pedido pago ser concluído.</small></p></div><div><i>3</i><p><b>Troque por recompensas</b><small>Use seu saldo nos benefícios disponíveis.</small></p></div></section><section className="loyalty-rewards"><div className="loyalty-title"><div><span>RECOMPENSAS</span><h3>{dados?.recompensas?.length?'Troque seus pontos':'Em breve por aqui'}</h3></div></div>{dados?.recompensas?.length?dados.recompensas.map(r=><div className="loyalty-reward-placeholder" key={r.id}><span>♡</span><div><b>{r.nome}</b><small>{r.descricao||'Recompensa do Clube Jeito de Mãe'}</small></div><strong>{r.pontos} pts</strong>{autenticado&&dados?.cliente&&saldo>=r.pontos&&<LoyaltyRedeem telefone={telefone} recompensa={r} onDone={async()=>{const {data}=await supabaseBrowser().auth.getSession();if(data.session)consultarConta(data.session.access_token)}}/>}</div>):<p>Estamos preparando benefícios especiais para quem pede sempre com a gente.</p>}</section>{dados?.movimentos?.length>0&&<section className="loyalty-rewards"><div className="loyalty-title"><div><span>HISTÓRICO</span><h3>Seus pontos</h3></div></div>{dados.movimentos.map(m=><div className="loyalty-history-row" key={m.id}><div><b>{m.descricao||'Movimento de pontos'}</b><small>{m.status}</small></div><strong>{m.pontos>0?'+':''}{m.pontos}</strong></div>)}</section>}</main><CustomerBottomNav/></div>;
}