'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import CustomerBottomNav from '@/components/CustomerBottomNav';
import DescadastroMarketing from './DescadastroMarketing';
import '../../loja-v15.css';
const KEY='jm_notificacoes';
const PADRAO={pedidos:true,novidades:false};
export default function Notificacoes(){const[prefs,setPrefs]=useState(PADRAO);useEffect(()=>{try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(d)setPrefs({...PADRAO,...d})}catch{}},[]);function mudar(k){setPrefs(p=>{const n={...p,[k]:!p[k]};try{localStorage.setItem(KEY,JSON.stringify(n))}catch{}return n})}return <><main className="customer-subpage settings-page"><header className="customer-subhead"><Link href="/conta">‹</Link><div><h1>Notificações</h1><p>Escolha o que você quer receber.</p></div></header><section className="settings-card"><button type="button" aria-pressed={prefs.pedidos} onClick={()=>mudar('pedidos')}><div><b>Atualizações do pedido</b><small>Recebido, preparo, saiu para entrega e concluído.</small></div><span className={`switch ${prefs.pedidos?'on':''}`}><i/></span></button><button type="button" aria-pressed={prefs.novidades} onClick={()=>mudar('novidades')}><div><b>Novidades do cardápio</b><small>Novos pratos e novidades da loja.</small></div><span className={`switch ${prefs.novidades?'on':''}`}><i/></span></button></section><DescadastroMarketing/><p className="settings-note">Os controles de avisos do pedido e novidades ficam salvos apenas neste aparelho. A preferência por mensagens promocionais é controlada separadamente no descadastro acima. Nenhuma opção desta tela autoriza campanhas externas. Avisos essenciais relacionados a um pedido em andamento podem continuar aparecendo dentro do acompanhamento do pedido.</p></main><CustomerBottomNav/></>}
