'use client';
import Link from 'next/link';
import { useEffect,useRef,useState } from 'react';
import CustomerBottomNav from '@/components/CustomerBottomNav';
import '../../loja-v15.css';
const V={nome:'',telefone:'',cep:'',endereco:'',numero:'',complemento:'',bairro:'',cidade:'',uf:''};
function maskCep(v){const n=String(v||'').replace(/\D/g,'').slice(0,8);return n.length>5?`${n.slice(0,5)}-${n.slice(5)}`:n}
export default function Endereco(){const[f,setF]=useState(V),[buscando,setBuscando]=useState(false),[erro,setErro]=useState(''),[ok,setOk]=useState(false),numeroRef=useRef(null),timer=useRef(null);useEffect(()=>{try{const d=JSON.parse(localStorage.getItem('jm_cliente')||'null');if(d)setF({...V,...d})}catch{}return()=>clearTimeout(timer.current)},[]);
 async function consultarCep(valor){const limpo=String(valor||'').replace(/\D/g,'').slice(0,8);setF(x=>({...x,cep:limpo}));setErro('');setOk(false);clearTimeout(timer.current);if(limpo.length!==8)return;timer.current=setTimeout(async()=>{setBuscando(true);try{const r=await fetch(`/api/cep/${limpo}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.erro||'Não foi possível consultar o CEP agora.');setF(x=>({...x,cep:limpo,endereco:d.endereco||x.endereco,bairro:d.bairro||x.bairro,cidade:d.cidade||x.cidade,uf:d.uf||x.uf}));setTimeout(()=>numeroRef.current?.focus(),120)}catch(e){setErro(e.message||'Não foi possível consultar o CEP agora. Você ainda pode preencher o endereço manualmente.')}finally{setBuscando(false)}},250)}
 function salvar(e){e.preventDefault();setErro('');if(f.cep.replace(/\D/g,'').length!==8||!f.endereco.trim()||!f.numero.trim()||!f.bairro.trim()){setErro('Confira CEP, rua, bairro e número da residência.');return}try{localStorage.setItem('jm_cliente',JSON.stringify(f));window.dispatchEvent(new Event('jm-cliente-atualizado'));setOk(true);setTimeout(()=>setOk(false),1800)}catch{setErro('Não foi possível salvar o endereço neste aparelho.')}}
 const resumo=f.endereco?`${f.endereco}${f.numero?`, ${f.numero}`:''}`:'Seu endereço aparecerá aqui';return <><main className="customer-subpage"><div className="customer-subhead"><Link href="/conta">‹</Link><div><h1>Endereço de entrega</h1><p>Informe onde você quer receber seu pedido.</p></div></div><form className="customer-card address-card" onSubmit={salvar}><label>CEP<input value={maskCep(f.cep)} onChange={e=>consultarCep(e.target.value)} inputMode="numeric" autoComplete="postal-code" placeholder="00000-000" maxLength={9}/></label>{buscando&&<small className="address-loading">Buscando endereço…</small>}{!!f.endereco&&<div className="address-preview"><span className="address-pin">⌖</span><div><b>{resumo}</b><small>{[f.bairro,f.cidade,f.uf].filter(Boolean).join(' · ')}</small></div></div>}<label>Rua<input value={f.endereco} onChange={e=>setF({...f,endereco:e.target.value})} autoComplete="address-line1" placeholder="Rua ou avenida"/></label><label>Bairro<input value={f.bairro} onChange={e=>setF({...f,bairro:e.target.value})} placeholder="Bairro"/></label><div className="address-row"><label>Número<input ref={numeroRef} value={f.numero} onChange={e=>setF({...f,numero:e.target.value})} inputMode="numeric" placeholder="Ex.: 394"/></label><label>Complemento<input value={f.complemento} onChange={e=>setF({...f,complemento:e.target.value})} autoComplete="address-line2" placeholder="Apto, bloco..."/></label></div>{!!f.cidade&&<small className="address-city">{f.cidade}{f.uf?` - ${f.uf}`:''}</small>}<div className="address-map-placeholder" aria-label="Localização do endereço"><span>⌖</span><div><b>{f.endereco?'Endereço localizado':'Localização da entrega'}</b><small>{f.endereco?`${resumo}${f.bairro?` · ${f.bairro}`:''}`:'Digite o CEP acima para localizar seu endereço.'}</small></div></div>{erro&&<div className="customer-error">{erro}</div>}<button disabled={buscando}>{buscando?'Consultando CEP…':'Salvar endereço'}</button>{ok&&<div className="customer-success">Endereço salvo ✓</div>}</form></main><CustomerBottomNav/></>}
