'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';

const CATEGORIAS = ['Pratos do dia', 'Bebidas', 'Sobremesas', 'Extras'];
const CART_KEY='jm_sacola_v15';
function brl(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function IconePrato(){return <span className="food-placeholder-mark">JM</span>}

export default function Loja({config,produtos}){
 const[catAtiva,setCatAtiva]=useState('Todos'),[busca,setBusca]=useState(''),[produtoSel,setProdutoSel]=useState(null),[opcaoSel,setOpcaoSel]=useState(0),[qtd,setQtd]=useState(1),[obs,setObs]=useState(''),[adicionaisSel,setAdicionaisSel]=useState([]),[talherSel,setTalherSel]=useState(null),[carrinho,setCarrinho]=useState([]),[cartReady,setCartReady]=useState(false),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[enviando,setEnviando]=useState(false),[erro,setErro]=useState(''),[pedidoFeito,setPedidoFeito]=useState(null),[pix,setPix]=useState(null),[pago,setPago]=useState(false),[cupomDigitado,setCupomDigitado]=useState(''),[cupomAplicado,setCupomAplicado]=useState(null),[erroCupom,setErroCupom]=useState(''),[validandoCupom,setValidandoCupom]=useState(false);const checkoutIdRef=useRef(null);
 const[form,setForm]=useState({nome:'',telefone:'',cep:'',endereco:'',numero:'',complemento:'',bairro:'',tipo:'entrega',pagamento:'pix',trocoPara:''});
 useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});try{const d=JSON.parse(localStorage.getItem('jm_cliente')||'null');if(d)setForm(f=>({...f,...d}));const c=JSON.parse(localStorage.getItem(CART_KEY)||'[]');if(Array.isArray(c))setCarrinho(c)}catch{}finally{setCartReady(true)}},[]);
 useEffect(()=>{if(!cartReady)return;try{localStorage.setItem(CART_KEY,JSON.stringify(carrinho))}catch{}},[carrinho,cartReady]);
 useEffect(()=>{if(modal!=='pix'||!pedidoFeito?.id)return;let ativo=true,timer;async function consultar(){try{const r=await fetch(`/api/pedidos/status?id=${encodeURIComponent(pedidoFeito.id)}`,{cache:'no-store'}),d=await r.json();if(ativo&&r.ok&&d.status_pagamento==='pago'){setPago(true);setModal('sucesso');clearInterval(timer)}}catch{}}consultar();timer=setInterval(consultar,3000);return()=>{ativo=false;clearInterval(timer)}},[modal,pedidoFeito?.id]);
 const aberto=!!config.aberto,taxaEntrega=Number(config.taxa_entrega||0);const subtotal=useMemo(()=>carrinho.reduce((s,i)=>s+Number(i.precoUnitario||0)*i.qtd,0),[carrinho]);const desconto=useMemo(()=>!cupomAplicado?0:cupomAplicado.tipo==='percentual'?subtotal*Number(cupomAplicado.valor||0)/100:Math.min(subtotal,Number(cupomAplicado.valor||0)),[cupomAplicado,subtotal]);const total=Math.max(0,subtotal-desconto)+(form.tipo==='entrega'?taxaEntrega:0);
 function avisar(msg){setToast(msg);setTimeout(()=>setToast(''),2200)}function abrirProduto(p){setProdutoSel(p);setOpcaoSel(0);setQtd(1);setObs('');setAdicionaisSel([]);setTalherSel(null);setModal('produto')}
 const produtoBase=produtoSel?(Array.isArray(produtoSel.opcoes)&&produtoSel.opcoes.length?Number(produtoSel.opcoes[opcaoSel]?.preco||0):Number(produtoSel.preco||0)):0;const adicionaisTotal=produtoSel?(Array.isArray(produtoSel.adicionais)?produtoSel.adicionais:[]).filter(a=>adicionaisSel.includes(a.nome)).reduce((s,a)=>s+Number(a.preco||0),0):0;const produtoTotal=(produtoBase+adicionaisTotal)*qtd;
 function adicionar(){const opcoes=Array.isArray(produtoSel.opcoes)?produtoSel.opcoes:[];const o=opcoes[opcaoSel]||{nome:'Único',preco:produtoSel.preco||0};const ad=(Array.isArray(produtoSel.adicionais)?produtoSel.adicionais:[]).filter(a=>adicionaisSel.includes(a.nome));if(produtoSel.perguntar_talher&&typeof talherSel!=='boolean'){avisar('Escolha se deseja talher descartável');return}const precoUnitario=Number((Number(o.preco)+ad.reduce((s,a)=>s+Number(a.preco||0),0)).toFixed(2));setCarrinho(c=>[...c,{key:`${produtoSel.id}-${Date.now()}`,produto_id:produtoSel.id,nome:produtoSel.nome,foto_url:produtoSel.foto_url||'',opcao:o.nome,adicionais:ad,observacao:obs,talher:talherSel,precoUnitario,qtd}]);setModal(null);avisar('Adicionado à sacola')}
 function removerItem(key){setCarrinho(c=>c.filter(i=>i.key!==key))}function mudarQtd(key,delta){setCarrinho(c=>c.map(i=>i.key===key?{...i,qtd:Math.max(1,i.qtd+delta)}:i))}function limparSacola(){setCarrinho([]);setCupomAplicado(null);setCupomDigitado('');setModal(null);avisar('Sacola esvaziada')}
 async function validarCupom(){setErroCupom('');setCupomAplicado(null);if(!cupomDigitado.trim())return;setValidandoCupom(true);try{const r=await fetch('/api/cupons/validar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({codigo:cupomDigitado.trim(),subtotal})}),d=await r.json();if(!r.ok)throw new Error(d.erro||'Cupom inválido');setCupomAplicado(d)}catch(e){setErroCupom(e.message)}finally{setValidandoCupom(false)}}
 async function buscarCep(){const cep=form.cep.replace(/\D/g,'');if(cep.length!==8)return;try{const r=await fetch(`/api/cep/${cep}`,{cache:'no-store'}),d=await r.json();if(r.ok)setForm(f=>({...f,endereco:d.endereco||f.endereco,bairro:d.bairro||f.bairro}))}catch{}}
 async function finalizarPedido(){setErro('');if(!form.nome.trim()||!form.telefone.trim())return setErro('Preencha nome e telefone.');if(form.tipo==='entrega'&&(!form.endereco.trim()||!form.numero.trim()||!form.bairro.trim()))return setErro('Preencha o endereço de entrega.');if(!carrinho.length)return setErro('Sua sacola está vazia.');setEnviando(true);try{if(!checkoutIdRef.current)checkoutIdRef.current=crypto.randomUUID();const payload={cliente_nome:form.nome.trim(),cliente_telefone:form.telefone.trim(),tipo:form.tipo,pagamento:form.pagamento,troco_para:form.pagamento==='dinheiro'?form.trocoPara:null,endereco:form.tipo==='entrega'?`${form.endereco}, ${form.numero}${form.complemento?` - ${form.complemento}`:''} - ${form.bairro} - CEP ${form.cep}`:null,itens:carrinho.map(({key,foto_url,...i})=>i),subtotal,desconto,taxa_entrega:form.tipo==='entrega'?taxaEntrega:0,total,cupom:cupomAplicado?.codigo||null,checkout_id:checkoutIdRef.current};const r=await fetch('/api/pedidos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),dados=await r.json();if(!r.ok)throw new Error(dados.erro||'Não foi possível enviar o pedido.');setPedidoFeito(dados.pedido);checkoutIdRef.current=null;setCarrinho([]);setCupomAplicado(null);setCupomDigitado('');if(dados.pix){setPix(dados.pix);setModal('pix');return}setPago(!!dados.cartao?.aprovado);setModal('sucesso')}catch(e){setErro(e?.message||'Falha de conexão. Tente novamente.')}finally{setEnviando(false)}}
 const diaAtual=(()=>{const n=new Intl.DateTimeFormat('en-US',{weekday:'long',timeZone:'America/Sao_Paulo'}).format(new Date());return{Monday:'segunda',Tuesday:'terca',Wednesday:'quarta',Thursday:'quinta',Friday:'sexta',Saturday:'sabado',Sunday:'domingo'}[n]})();const visiveis=produtos.filter(p=>p.ativo!==false&&(Array.isArray(p.dias_semana)?p.dias_semana:[]).includes(diaAtual));const filtrados=visiveis.filter(p=>!busca.trim()||`${p.nome||''} ${p.descricao||''}`.toLowerCase().includes(busca.trim().toLowerCase()));const cats=catAtiva==='Todos'?CATEGORIAS.filter(c=>filtrados.some(p=>p.categoria===c)):[catAtiva];const catsDisponiveis=['Todos',...CATEGORIAS.filter(c=>visiveis.some(p=>p.categoria===c))];const qtdCarrinho=carrinho.reduce((s,i)=>s+i.qtd,0);const Foto=({p,tam=34})=>p?.foto_url?<img src={p.foto_url} alt={p.nome} loading="lazy"/>:<IconePrato tam={tam}/>;
 return <>
 <header className="store-head">
   <button className="store-address" type="button"><span className="store-pin">⌖</span><span><small>Entregar em</small><b>Informe seu endereço</b></span><i>›</i></button>
   <div className="store-banner" style={config.banner_url?{backgroundImage:`linear-gradient(180deg,rgba(45,8,12,.18),rgba(45,8,12,.48)),url("${config.banner_url}")`}:undefined}></div>
   <div className="store-hero">
     <div className="store-logo"><img src="/jeito%20de%20m%C3%A3e%20logo%20new.png" alt="Jeito de Mãe"/></div>
     <div className="store-title-row"><div><h1>Jeito de Mãe</h1><p>Delícias Caseiras</p></div><Link href="/conta" className="store-profile" aria-label="Abrir conta">♡</Link></div>
     <div className="store-meta"><span className={`store-open ${aberto?'on':'off'}`}><i></i>{aberto?'Aberto agora':'Fechado'}</span><span>{config.horario||'11h às 16h · Seg a Sáb'}</span>{aberto&&<span>Entrega em {config.tempo_entrega||'30–60 min'}</span>}</div>
   </div>
 </header>
 <section className="smart-home">
   <div className="smart-banner">
     <div className="smart-banner-copy"><span className="smart-kicker">DESTAQUE DE HOJE</span><h2>Comida com aquele sabor de casa.</h2><p>Escolha seu prato favorito e peça sem sair daqui.</p><button type="button" onClick={()=>document.querySelector('.store-search')?.scrollIntoView({behavior:'smooth'})}>Ver cardápio <b>→</b></button></div>
     <div className="smart-banner-art" aria-hidden="true"><span>JM</span></div>
   </div>
   <div className="home-benefits">
     <article><span className="benefit-icon">✦</span><div><b>Fidelidade</b><small>Em breve, seus pedidos vão valer pontos.</small></div><span className="benefit-soon">Em breve</span></article>
     <article><span className="benefit-icon">♡</span><div><b>Feito com carinho</b><small>Pratos preparados com sabor de comida caseira.</small></div></article>
   </div>
 </section>
 {!aberto&&<div className="wrap"><div className="closed-banner"><b>Loja fechada no momento.</b> Você pode consultar o cardápio e voltar no horário de atendimento.</div></div>}
 <div className="store-tabs"><button className="active">Cardápio</button><Link href="/meus-pedidos">Meus pedidos</Link></div>
 <div className="store-search"><span>⌕</span><input aria-label="Buscar no cardápio" placeholder="Buscar no cardápio" value={busca} onChange={e=>setBusca(e.target.value)}/></div>
 <nav className="cats"><div className="cats-in wrap">{catsDisponiveis.map(c=><button key={c} className={`cat ${catAtiva===c?'active':''}`} onClick={()=>setCatAtiva(c)}>{c}</button>)}</div></nav>
 <main className="wrap">{cats.map(cat=><section key={cat}><h2 className="sec">{cat}</h2><div className="grid">{filtrados.filter(p=>p.categoria===cat).map(p=><button className="card" key={p.id} onClick={()=>abrirProduto(p)}><div className="card-body">{p.destaque&&<span className="tag">Destaque</span>}<h3>{p.nome}</h3><p>{p.descricao}</p><div className="price">{Array.isArray(p.opcoes)&&p.opcoes.length?`A partir de ${brl(Math.min(...p.opcoes.map(o=>Number(o.preco))))}`:brl(p.preco)}</div></div><div className={`thumb card-photo ${p.foto_url?'has-photo':'no-photo'}`}><Foto p={p}/>{p.destaque&&<span className="photo-badge">Destaque</span>}</div></button>)}</div></section>)}{!filtrados.length&&<div className="empty">{busca?'Nenhum item encontrado.':'Nenhum item disponível para hoje.'}</div>}</main>
 {!!qtdCarrinho&&<div className="cartbar"><div className="cartbar-in wrap"><button className="btn" onClick={()=>setModal('carrinho')}><span>Ver sacola <span className="count">{qtdCarrinho}</span></span><b>{brl(subtotal)}</b></button></div></div>}
 {modal==='produto'&&produtoSel&&<div className="product-app" role="dialog" aria-modal="true"><div className="product-app-top"><button className="product-back" onClick={()=>setModal(null)}>‹</button></div>{produtoSel.foto_url?<div className="product-cover"><img src={produtoSel.foto_url} alt={produtoSel.nome}/></div>:<div className="product-cover product-cover-empty"><IconePrato tam={62}/></div>}<div className="product-content"><h1>{produtoSel.nome}</h1>{produtoSel.descricao&&<p className="product-description">{produtoSel.descricao}</p>}<strong className="product-price">{brl(produtoBase)}</strong>{Array.isArray(produtoSel.opcoes)&&produtoSel.opcoes.length>0&&<section className="product-section"><div className="product-section-title"><div><b>Escolha uma opção</b><small>Selecione 1 opção</small></div><span>Obrigatório</span></div>{produtoSel.opcoes.map((o,idx)=><label className="product-choice" key={o.nome}><div><b>{o.nome}</b><small>{brl(o.preco)}</small></div><input type="radio" checked={opcaoSel===idx} onChange={()=>setOpcaoSel(idx)}/></label>)}</section>}{Array.isArray(produtoSel.adicionais)&&produtoSel.adicionais.length>0&&<section className="product-section"><div className="product-section-title"><div><b>Adicionais</b><small>Escolha como preferir</small></div><span className="optional">Opcional</span></div>{produtoSel.adicionais.map(a=><label className="product-choice" key={a.nome}><div><b>{a.nome}</b><small>+ {brl(a.preco)}</small></div><input type="checkbox" checked={adicionaisSel.includes(a.nome)} onChange={()=>setAdicionaisSel(s=>s.includes(a.nome)?s.filter(x=>x!==a.nome):[...s,a.nome])}/></label>)}</section>}{produtoSel.perguntar_talher&&<section className="product-section"><div className="product-section-title"><div><b>Precisa de talher?</b><small>Escolha uma opção</small></div><span>Obrigatório</span></div><label className="product-choice"><b>Sim, enviar talher</b><input type="radio" name="talher" checked={talherSel===true} onChange={()=>setTalherSel(true)}/></label><label className="product-choice"><b>Não preciso</b><input type="radio" name="talher" checked={talherSel===false} onChange={()=>setTalherSel(false)}/></label></section>}<section className="product-section product-note"><b>Alguma observação?</b><textarea placeholder="Ex.: tirar cebola, molho separado..." value={obs} onChange={e=>setObs(e.target.value)} maxLength={140}/><small>{obs.length}/140</small></section></div><div className="product-action"><div className="product-qty"><button onClick={()=>setQtd(Math.max(1,qtd-1))}>−</button><b>{qtd}</b><button onClick={()=>setQtd(qtd+1)}>+</button></div><button className="product-add" onClick={adicionar}><span>Adicionar</span><b>{brl(produtoTotal)}</b></button></div></div>}
 {modal==='carrinho'&&<div className="cart-app" role="dialog" aria-modal="true"><header className="cart-app-head"><button onClick={()=>setModal(null)}>‹</button><div><h2>Sua sacola</h2><small>{qtdCarrinho} {qtdCarrinho===1?'item':'itens'}</small></div><button className="cart-clear" onClick={limparSacola}>Esvaziar</button></header><div className="cart-app-body">{carrinho.map(i=><article className="bag-item" key={i.key}>{i.foto_url?<img src={i.foto_url} alt=""/>:<div className="bag-placeholder"><IconePrato tam={26}/></div>}<div className="bag-info"><b>{i.nome}</b>{i.opcao&&i.opcao!=='Único'&&<small>{i.opcao}</small>}{i.adicionais?.length>0&&<small>+ {i.adicionais.map(a=>a.nome).join(', ')}</small>}{i.observacao&&<small className="bag-note">“{i.observacao}”</small>}<strong>{brl(i.precoUnitario*i.qtd)}</strong></div><div className="bag-controls"><button onClick={()=>i.qtd===1?removerItem(i.key):mudarQtd(i.key,-1)}>{i.qtd===1?'×':'−'}</button><b>{i.qtd}</b><button onClick={()=>mudarQtd(i.key,1)}>+</button></div></article>)}<button className="bag-more" onClick={()=>setModal(null)}>+ Adicionar mais itens</button><section className="bag-coupon"><b>Tem um cupom?</b><div><input placeholder="CUPOM" value={cupomDigitado} onChange={e=>setCupomDigitado(e.target.value.toUpperCase())}/><button onClick={validarCupom} disabled={validandoCupom}>{validandoCupom?'...':'Aplicar'}</button></div>{erroCupom&&<small className="erro">{erroCupom}</small>}{cupomAplicado&&<small className="bag-coupon-ok">Cupom aplicado ✓</small>}</section><section className="bag-summary"><span>Subtotal <b>{brl(subtotal)}</b></span>{desconto>0&&<span>Desconto <b>− {brl(desconto)}</b></span>}<span>Taxa de entrega <b>{form.tipo==='entrega'?brl(taxaEntrega):'R$ 0,00'}</b></span><span className="bag-total">Total <b>{brl(total)}</b></span></section></div><footer className="cart-app-action"><button onClick={()=>setModal('checkout')}><span>Continuar</span><b>{brl(total)}</b></button></footer></div>}
 {modal==='checkout'&&<div className="checkout-app" role="dialog" aria-modal="true">
   <header className="checkout-head"><button onClick={()=>setModal('carrinho')}>‹</button><div><h2>Finalizar pedido</h2><small>Revise seus dados e escolha como receber</small></div></header>
   <div className="checkout-body">
    <section className="checkout-section"><div className="checkout-section-title"><span>1</span><div><b>Como você quer receber?</b><small>Escolha entrega ou retirada</small></div></div><div className="checkout-segment"><button className={form.tipo==='entrega'?'active':''} onClick={()=>setForm({...form,tipo:'entrega'})}>Entrega</button><button className={form.tipo==='retirada'?'active':''} onClick={()=>setForm({...form,tipo:'retirada'})}>Retirada</button></div></section>
    <section className="checkout-section"><div className="checkout-section-title"><span>2</span><div><b>Seus dados</b><small>Usaremos para identificar seu pedido</small></div></div><div className="checkout-fields"><label><span>Nome</span><input placeholder="Seu nome" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></label><label><span>WhatsApp</span><input placeholder="(11) 99999-9999" value={form.telefone} onChange={e=>setForm({...form,telefone:e.target.value})}/></label></div></section>
    {form.tipo==='entrega'&&<section className="checkout-section"><div className="checkout-section-title"><span>3</span><div><b>Endereço de entrega</b><small>Informe onde devemos entregar</small></div></div><div className="checkout-fields"><label><span>CEP</span><input placeholder="00000-000" value={form.cep} onChange={e=>setForm({...form,cep:e.target.value})} onBlur={buscarCep}/></label><label><span>Endereço</span><input placeholder="Rua, avenida..." value={form.endereco} onChange={e=>setForm({...form,endereco:e.target.value})}/></label><div className="checkout-row"><label><span>Número</span><input placeholder="123" value={form.numero} onChange={e=>setForm({...form,numero:e.target.value})}/></label><label><span>Complemento</span><input placeholder="Apto, casa..." value={form.complemento} onChange={e=>setForm({...form,complemento:e.target.value})}/></label></div><label><span>Bairro</span><input placeholder="Seu bairro" value={form.bairro} onChange={e=>setForm({...form,bairro:e.target.value})}/></label></div></section>}
    <section className="checkout-section"><div className="checkout-section-title"><span>{form.tipo==='entrega'?'4':'3'}</span><div><b>Pagamento</b><small>Escolha a forma de pagamento</small></div></div><div className="checkout-payments">{[['pix','PIX','Pagamento rápido'],['credito','Cartão','Crédito'],['dinheiro','Dinheiro','Pague na entrega']].map(([p,t,s])=><button key={p} className={form.pagamento===p?'active':''} onClick={()=>setForm({...form,pagamento:p})}><i>{p==='pix'?'◆':p==='credito'?'▭':'$'}</i><span><b>{t}</b><small>{s}</small></span><em>{form.pagamento===p?'✓':''}</em></button>)}</div></section>
    <section className="checkout-section checkout-coupon"><div><b>Cupom de desconto</b><small>Tem um código? Aplique antes de finalizar.</small></div><div className="checkout-coupon-row"><input placeholder="CUPOM" value={cupomDigitado} onChange={e=>setCupomDigitado(e.target.value.toUpperCase())}/><button onClick={validarCupom} disabled={validandoCupom}>{validandoCupom?'...':'Aplicar'}</button></div>{erroCupom&&<small className="erro">{erroCupom}</small>}{cupomAplicado&&<small className="bag-coupon-ok">Cupom aplicado ✓</small>}</section>
    <section className="checkout-summary"><h3>Resumo</h3><span>Subtotal <b>{brl(subtotal)}</b></span>{desconto>0&&<span className="discount">Desconto <b>− {brl(desconto)}</b></span>}<span>{form.tipo==='entrega'?'Taxa de entrega':'Retirada'} <b>{form.tipo==='entrega'?brl(taxaEntrega):'Grátis'}</b></span><span className="checkout-total">Total <b>{brl(total)}</b></span></section>
    {erro&&<div className="checkout-error">{erro}</div>}
   </div>
   <footer className="checkout-action"><button disabled={enviando||!aberto} onClick={finalizarPedido}><span>{enviando?'Enviando...':aberto?'Fazer pedido':'Loja fechada'}</span><b>{brl(total)}</b></button></footer>
 </div>}
 {modal==='pix'&&pix&&<div className="sheet"><div className="sheet-card"><div className="sheet-head"><h3>Pagamento Pix</h3></div><div className="sheet-body"><div className="pix-box">{pix.qr_code_base64&&<img src={`data:image/png;base64,${pix.qr_code_base64}`} alt="QR Code Pix"/>}<textarea className="inp" readOnly value={pix.qr_code||''}/></div></div></div></div>}
 {modal==='sucesso'&&pedidoFeito&&<div className="sheet"><div className="sheet-card"><div className="sheet-head"><h3>Pedido recebido!</h3></div><div className="sheet-body"><div className="success"><b>Pedido {pedidoFeito.codigo}</b><p>{pago?'Pagamento confirmado. ':'Recebemos seu pedido. '}</p><a className="btn" href={`/pedido/${pedidoFeito.id}`}>Acompanhar pedido</a></div></div></div></div>}{toast&&<div className="toast">{toast}</div>}
 </>;
}}</i><span><b>{t}</b><small>{s}</small></span><em>{form.pagamento===p?'✓':''}</em></button>)}</div></section>
    <section className="checkout-section checkout-coupon"><div><b>Cupom de desconto</b><small>Tem um código? Aplique antes de finalizar.</small></div><div className="checkout-coupon-row"><input placeholder="CUPOM" value={cupomDigitado} onChange={e=>setCupomDigitado(e.target.value.toUpperCase())}/><button onClick={validarCupom} disabled={validandoCupom}>{validandoCupom?'...':'Aplicar'}</button></div>{erroCupom&&<small className="erro">{erroCupom}</small>}{cupomAplicado&&<small className="bag-coupon-ok">Cupom aplicado ✓</small>}</section>
    <section className="checkout-summary"><h3>Resumo</h3><span>Subtotal <b>{brl(subtotal)}</b></span>{desconto>0&&<span className="discount">Desconto <b>− {brl(desconto)}</b></span>}<span>{form.tipo==='entrega'?'Taxa de entrega':'Retirada'} <b>{form.tipo==='entrega'?brl(taxaEntrega):'Grátis'}</b></span><span className="checkout-total">Total <b>{brl(total)}</b></span></section>
    {erro&&<div className="checkout-error">{erro}</div>}
   </div>
   <footer className="checkout-action"><button disabled={enviando||!aberto} onClick={finalizarPedido}><span>{enviando?'Enviando...':aberto?'Fazer pedido':'Loja fechada'}</span><b>{brl(total)}</b></button></footer>
 </div>}
 {modal==='pix'&&pix&&<div className="sheet"><div className="sheet-card"><div className="sheet-head"><h3>Pagamento Pix</h3></div><div className="sheet-body"><div className="pix-box">{pix.qr_code_base64&&<img src={`data:image/png;base64,${pix.qr_code_base64}`} alt="QR Code Pix"/>}<textarea className="inp" readOnly value={pix.qr_code||''}/></div></div></div></div>}
 {modal==='sucesso'&&pedidoFeito&&<div className="sheet"><div className="sheet-card"><div className="sheet-head"><h3>Pedido recebido!</h3></div><div className="sheet-body"><div className="success"><b>Pedido {pedidoFeito.codigo}</b><p>{pago?'Pagamento confirmado. ':'Recebemos seu pedido. '}</p><a className="btn" href={`/pedido/${pedidoFeito.id}`}>Acompanhar pedido</a></div></div></div></div>}{toast&&<div className="toast">{toast}</div>}
 </>;
}