'use client';
import { useState } from 'react';

const dataLocal=v=>v?new Date(v).toISOString().slice(0,16):'';
export default function MarketingBannerList({iniciais=[]}){
 const [banners,setBanners]=useState(iniciais),[busy,setBusy]=useState(''),[editando,setEditando]=useState(null),[form,setForm]=useState(null),[erro,setErro]=useState('');
 const alterar=async(id,acao)=>{setBusy(id+acao);setErro('');try{const r=await fetch('/api/admin/banners/'+id,{method:acao==='excluir'?'DELETE':'PATCH',headers:{'Content-Type':'application/json'},body:acao==='excluir'?undefined:JSON.stringify({ativo:acao==='ativar'})});const j=await r.json();if(!r.ok)throw new Error(j.erro||'Falha ao atualizar');if(acao==='excluir')setBanners(x=>x.filter(b=>b.id!==id));else setBanners(x=>x.map(b=>b.id===id?j.banner:b));}catch(e){setErro(e.message)}finally{setBusy('')}};
 const abrir=b=>{setEditando(b.id);setForm({kicker:b.kicker||'',titulo:b.titulo||'',texto:b.texto||'',cta:b.cta||'',link:b.link||'/',imagem:b.imagem_url||'',inicio:dataLocal(b.inicio_em),fim:dataLocal(b.fim_em),prioridade:String(b.prioridade||1)});setErro('')};
 const salvar=async()=>{setBusy('edit');setErro('');try{const r=await fetch('/api/admin/banners/'+editando,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw new Error(j.erro||'Falha ao salvar');setBanners(x=>x.map(b=>b.id===editando?j.banner:b));setEditando(null);setForm(null)}catch(e){setErro(e.message)}finally{setBusy('')}};
 if(!banners.length)return <div className="marketing-empty"><div>▧</div><h3>Seu primeiro banner começa aqui</h3><p>Divulgue feijoada, prato do dia, promoções ou novidades diretamente na página inicial.</p></div>;
 return <>{erro&&<div className="banner-admin-error">{erro}</div>}<div className="banner-admin-list">{banners.map(b=><article key={b.id}><div className="banner-admin-thumb" style={b.imagem_url?{backgroundImage:`url("${b.imagem_url}")`}:undefined}>✦</div><div className="banner-admin-copy"><small>{b.kicker||'CAMPANHA'}</small><b>{b.titulo}</b><span>{b.ativo?'Ativo na loja':'Rascunho'} · prioridade {b.prioridade}</span></div><div className="banner-admin-actions"><button disabled={!!busy} onClick={()=>abrir(b)}>Editar</button><button disabled={!!busy} onClick={()=>alterar(b.id,b.ativo?'desativar':'ativar')}>{b.ativo?'Desativar':'Ativar'}</button><button className="danger" disabled={!!busy} onClick={()=>alterar(b.id,'excluir')}>Excluir</button></div></article>)}</div>{editando&&form&&<div className="banner-edit-modal"><div className="banner-edit-card"><header><div><small>EDITAR CAMPANHA</small><h3>{form.titulo}</h3></div><button onClick={()=>setEditando(null)}>×</button></header><label>Chamada<input value={form.kicker} onChange={e=>setForm({...form,kicker:e.target.value})}/></label><label>Título<input value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})}/></label><label>Texto<textarea value={form.texto} onChange={e=>setForm({...form,texto:e.target.value})}/></label><div className="banner-form-row"><label>Botão<input value={form.cta} onChange={e=>setForm({...form,cta:e.target.value})}/></label><label>Destino<input value={form.link} onChange={e=>setForm({...form,link:e.target.value})}/></label></div><label>Imagem<input value={form.imagem} onChange={e=>setForm({...form,imagem:e.target.value})}/></label><div className="banner-form-row"><label>Início<input type="datetime-local" value={form.inicio} onChange={e=>setForm({...form,inicio:e.target.value})}/></label><label>Fim<input type="datetime-local" value={form.fim} onChange={e=>setForm({...form,fim:e.target.value})}/></label></div><label>Prioridade<select value={form.prioridade} onChange={e=>setForm({...form,prioridade:e.target.value})}><option value="1">Normal</option><option value="2">Alta</option><option value="3">Principal</option></select></label><footer><button onClick={()=>setEditando(null)}>Cancelar</button><button className="primary" disabled={busy==='edit'||!form.titulo.trim()} onClick={salvar}>{busy==='edit'?'Salvando...':'Salvar alterações'}</button></footer></div></div>}</>;
}
